# -*- coding: utf-8 -*-
"""Yahoo_RSS_Media_2021-03-30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10OE3BNH_9r8nzs5ufn8fHUvTLay6hj-y
"""



#Yahoo_RSS_Media 見出しスクレイピング 2021-03-29現在
#対象約600サイト、所要10分程度、1・5Ｍ

import pandas as pd
import requests
from bs4 import BeautifulSoup
import re
import csv

df = pd.read_csv( '/content/yahoo_media_list.csv') 

with open("/content/Yahoo_RSS_Media.csv", mode="a", encoding="utf_8_sig",newline='') as f:
  writer = csv.DictWriter(f, ['Media','Title','Link','Pubdate', 'Description'])
  writer.writeheader()
 
  for index, row in df.iterrows():
    url = row['url'] 
    xml = requests.get( url )
    soup = BeautifulSoup(xml.text, 'xml' )

    for news in soup.findAll('item'):
      d = {}
      d["Media"]  = row['media'] 
      d["Title"]  = news.title.string
      d["Link"] = news.link.string
      d["Pubdate"] = news.pubDate.string
      d["Description"]  = "" if news.description == None else news.description.string
      writer.writerow(d)